-- qType — seed dictionary sources from sq_source.json
-- Generated; safe to re-run (INSERT IGNORE).
-- IMPORTANT: load with --default-character-set=utf8mb4 or use the .NET importer
--   (mysql --default-character-set=utf8mb4 -uroot -p < 002_seed_sources.sql)
--   or:  dotnet run --project src/QType.Importer -- sources

USE qtype_db;
SET NAMES utf8mb4;

START TRANSACTION;
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (1, 'Г. Мамырбекова. Қазақ тіліндегі араб, парсы сөздерінің түсіндірме сөздігі. – Алматы. 2017. 658 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (2, 'С.Құлманов. Орысша-қазақша терминологиялық анықтамалық сөздік (сәулет және құрылыс). – Алматы: Мемлекеттік тілді дамыту орталығы, 2009. – 320 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (3, 'Б.Құсбекова. Орысша-қазақша терминологиялық анықтамалық сөздік (білім беру саласы).– Алматы:Мемлекеттік тілді дамыту орталығы, 2010. – 304 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (4, 'С.Құлманов. Орысша-қазақша терминологиялық анықтамалық сөздік (халықты жұмыспен қамту және әлеуметтік қорғау саласы). – Алматы: Мемлекеттік тілді дамыту орталығы, 2009. –344 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (5, 'А. Болатжан. Орысша-қазақша терминологиялық анықтамалық сөздік (заң және құқық саласы).– Алматы: Мемлекеттік тілді дамыту орталығы, 2010. –324 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (6, 'Г. Ильясова. Орысша-қазақша терминологиялық анықтамалық сөздік (ақпараттық жүйе саласы).– Алматы: Мемлекеттік тілді дамыту орталығы, 2010. 312 - б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (7, 'А.Баймашев. Орысша-қазақша терминологиялық анықтамалық сөздік (кеден саласы).– Алматы: Мемлекеттік тілді дамыту орталығы, 2009. –250 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (8, '', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (209, 'Қазақ әдеби тілінің сөздігі. Он бес томдық. 5 - том / Құраст.: Б. Әбілқасымов, С.Бизақов, Ә.Жүнiсбеков және т.б. - Алматы, 2011. - 752 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (102, 'Ботаникадан қысқаша терминдік сөздік / Г.Н. Паршина, Г.С. Айнагулова, Г.С. Нурмухамбетова - Астана: Л.Н. Гумилев атындағы ЕҰУ, 2013. - 82 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (9, 'Б.Құсбекова. Орысша-қазақша терминологиялық анықтамалық сөздік (сақтандыру саласы).– Алматы: Мемлекеттік тілді дамыту институты, 2010. – 316 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (10, 'Зағыпаров Қ.Ф. Философиялық терминдердің сөздігі. - Павлодар: ПМПИ, 2011. – 138 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (11, 'С.Құлманов. Орысша-қазақша терминологиялық анықтамалық сөздік (қаржы саласы).–  5-кітап.– Алматы: Мемлекеттік тілді дамыту орталығы ЖШС, 2009. 336 - бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (13, 'Қазақ әдеби тілінің сөздігі. Он бес томдық. 6 - том / Құраст.: Ж. Қоңыратбаева, Ғ.Қалиев, Қ.Есенова  және т.б. - Алматы, 2011. - 752 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (14, 'Б.Қалиев. Қазақ тілінің түсіндірме сөздігі. Алматы, 2014. - 728 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (15, 'Бизақов С. Синонимдер сөздігі. - Алматы: Арыс баспасы, 2007. - 640 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (16, 'Г. Мамырбекова, А.Сейтбекова. Әбілғазы баһадүр ханның «Түркі шежіресінің» тезаурус сөздігі. Алматы: «Фирма Орнак», 2013. - 480 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (17, 'Қ.Б. Жарықбаев. Жантану атауларының түсіндірме сөздігі. Сөздік словарь баспасы. 2006. - 387 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (18, 'Ислам энциклопедиясы / Бас редактор Р. Нұрғалиев. - Алматы: Қазақ энциклопедиясы Бас редакциясы, 1995. - 306 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (19, 'Журналист Тоқан Бодаухан ұсынған сөздер', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (20, 'Қоңыров Т. Тұрақты теңеулер сөздігі. – Алматы: «Арыс» баспасы, 2007. - 480 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (21, 'Д.Қамзабекұлы. Ескі қазақ әдеби тілінің түсіндірме сөздігі (кірме сөздер). 2 том. Астана полиграфия баспасы, 2011. - 304 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (22, 'А. Ысқақов, Р. Сыздықова, Ш. Сарыбаев. Қазақ тілінің қысқаша этимологиялық сөздігі, Қазақ ССР-ның «Ғылым» баспасы, Алматы -1966. - 240 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (23, 'Е.Тоғжанов. Этносаяси сөздік. Астана, 2014. - 400 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (24, 'Ахмет Байтұрсынұлы. Энциклопедия / бас ред. Тойбаева Ж. - Алматы: Қазақ энциклопедиясы, 2017. - 744 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (25, 'Т. Жанұзақ. Қазақ есімдерінің анықтамалығы. – Алматы: «Арыс» баспасы, 2009. – 552 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (26, 'Қашқари М. Түрік сөздігі. 1-том / Аударған А. Егеубай. - Алматы: Арда+7, 2017. - 592 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (27, 'Қашқари М. Түрік сөздігі. 2-том / Аударған А. Егеубай. - Алматы: Арда+7, 2017. - 528 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (28, 'Қашқари М. Түрік сөздігі. 3-том / Аударған А. Егеубай. - Алматы: Арда+7, 2017. - 600 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (29, 'Е.Тілешов, Д.Қамзабекұлы. Алаш қозғалысы. Энциклопедиялық анықтамалық. Алматы: Сардар, 2014. - 528 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (30, 'Шваб Клаус. Төртінші индустриялық революция. - Алматы: Ұлттық аударма бюросы, 2018. - 200 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (35, 'Қазақ әдеби тілінің сөздігі. Он бес томдық. 1-том. / Құраст. Т.Жанұзақ, С.Омарбеков, Ә.Жүнісбек және т.б. - Алматы, 2011. - 752 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (36, 'Сыздықова Р., Ясауи Хикметтерінің тілі. Көптомдық шығармалар жинағы / Рәбиға Сыздықова. / - Алматы: Ел-шежіре, 2014. - 667 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (37, 'Компьютерлік инциденттерге әрекет ету орталығы ұсынған сөздіктер', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (38, 'Қазақ әдеби тілінің сөздігі. Он бес томдық. 2-том / Құраст. Ғ.Қалиев, С.Бизақов, О. Нақысбеков және т.б. - Алматы, 2011. - 744 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (39, 'Ақбай Н.Е. Абай жолы энциклопедиясы', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (40, 'Қазақ әдеби тілінің сөздігі. Он бес томдық. 10-том. / Құраст.: М.Малбақов, Н.Оңғарбаева, А.Үдербаев және т.б. – Алматы, 2011. -752 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (41, 'Қазақ әдеби тілінің сөздігі. Он бес томдық. 11-том. /Құраст.: Ж.Манкеева, С.Бизақов, Ә.Жүнісбек және т.б. - Алматы, 2011. - 752 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (44, 'Әлеуметтанудың түсіндірме сөздігі. – Алматы: Сөздік-словарь, 2007. - 344 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (48, 'Философиялық сөздік. Редкол: Р. Н. Нұрғалиев. Алматы: Қазақ энц. баспасы. 1996. - 525 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (49, 'С.Бизақов, Ә.Болғанбаев, Ш.Дәулетқұлов. Қазақ тілінің синонимдер сөздігі. – Алматы: «Арыс» баспасы, 2005. - 720 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (51, 'Профессор Гүлмира Сұлтанбаева ұсынған сөздер', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (53, 'М.Белбаева. Қазақ тілінің омонимдер сөздігі: – Алматы: «Мектеп» баспасы, 1988. - 193 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (54, '', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (210, 'Физикалық географияның терминдері мен ұғымдары. Оқу құралы / Жанәділ О. – Алматы: «Дәуір-Кітап» баспасы, 2014. - 86 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (55, 'Б Қалиев, Ж. Түймебаев, Ш. Құрманбайұлы, С. Исакова. Мұқағали тілі сөздігі. – Алматы, 2017', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (57, 'Қазақ әдеби тілінің сөздігі. Он бес томдық. 4-том. / Құраст.: Н.Әшімбаева, Қ.Рысбергенова, Ж.Манкеева және т.б. – Алматы, 2011. 752 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (58, 'Қазақ әдеби тілінің сөздігі. Он бес томдық. 7-том. / Құраст.: Б.Момынова, Б.Сүйерқұлова, А. Фазылжанова және т.б. – Алматы, 2011. 752 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (59, 'Әдебиеттану терминдерінің сөздігі. Алматы: «Ана тілі» баспасы, 1998. - 384 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (61, 'Қазақ әдеби тілінің сөздігі. Он бес томдық. 14-том. / Құраст.: М.Малмақов, Қ.Есенова, Б.Хинаят және т.б. – Алматы, 2011. 800 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (62, 'Қазақ әдеби тілінің сөздігі. Он бес томдық. 14-том. / Құраст.: М.Малмақов, Қ.Есенова, Б.Хинаят және т.б. – Алматы, 2011. - 800 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (65, 'Профессор Гүлмира Сұлтанбаева ұсынған сөздер', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (66, 'Қазақ әдеби тілінің сөздігі. Он бес томдық. 3-том. / Құраст.: Б. Сүйерқұлова, Т.Жанұзақ, О.Жұбаева және т.б. – Алматы, 2011. - 744 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (67, 'Қазақ әдеби тілінің  сөздігі. Он бес томдық. / Құраст. Т. Жанұзақ, С.Омарбеков, Ә.Жүнісбек және т.б. – Алматы, 2011- 5-том. 752 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (68, 'Қазақ әдеби тілінің сөздігі. Он бес томдық. 5-том. / Құраст.: Б.Әбілқасымов, С.Бизақов, Ә.Жүнісбеков және т.б. – Алматы, 2011. -752 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (69, 'Қазақ әдеби тілінің сөздігі. Он бес томдық. 9-том. / Құраст.: Ә.Ыбырайым, А.Жаңабекова, Қ.Рысбергенова және т.б. – Алматы, 2011. -744 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (71, 'Профессор Қаржаубай Сартқожаұлы ұсынған сөздер', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (72, 'Қазақ тілінің аймақтық сөздігі /Құраст. Ғ.Қалиев, О.Нақысбеков, Ш.Сарыбаев, А.Үдербаев және т.б. – Алматы: «Арыс» баспасы, 2005. - 824 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (73, 'Қазақ тілінің аймақтық сөздігі /Құраст. Ғ.Қалиев, О.Нақысбеков, Ш.Сарыбаев, А.Үдербаев және т.б. – Алматы: «Арыс» баспасы, 2005. - 824 бет', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (75, 'Қазақ тілінің аймақтық сөздігі /Құраст. Ғ.Қалиев, О.Нақысбеков, Ш.Сарыбаев, А.Үдербаев және т.б. – Алматы: «Арыс» баспасы, 2005. - 824 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (87, 'Қазақ әдеби тілінің сөздігі. Он бес томдық. 13-том / Құраст. А. Фазылжанова, Н. Оңғарбаева, Қ. Ғабитханұлы және т.б. - Алматы, 2011. - 752 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (77, 'Қазақ әдеби тілінің сөздігі. Он бес томдық. 12-том / Құраст. А.Үдербаев, О.Нақысбеков, Ж.Қоңыратбаева және т.б. - Алматы, 2011. - 752 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (79, 'Қазақтың этнографиялық категориялар, ұғымдар мен атауларының дәстүрлі жүйесі. Энциклопедия. 1-том. – Алматы: DPS, 2011. – 738 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (89, 'Қазақтың этнографиялық категориялар, ұғымдар мен атауларының дәстүрлі жүйесі. Энциклопедия. 3-том. – Алматы: РПК &quot;Слон&quot; DPS, 2012. – 736 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (84, 'Қазақтың этнографиялық категориялар, ұғымдар мен атауларының дәстүрлі жүйесі. Энциклопедия. 2-том. – Алматы: РПК &quot;Слон&quot; DPS, 2012. – 736 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (90, 'Кеңесбаев І. Фразеологиялық сөздік. - Алматы: "Арыс" баспасы, 2007. - 800 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (94, 'Бринкерхов Д., Уейтс Р., Ортега С. Әлеуметтану негіздері, 9-басылым. Алматы: Ұлттық аударма бюросы, 2018 жыл -464 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (95, 'Мэнкью Грегори Н., Тейлор Марк П. Экономикс, 4-халықаралық басылым. Алматы: Ұлттық аударма бюросы, 2018 жыл – 848 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (96, 'Армстронг К., Иудаизм, христиандық пен исламдағы 4000 жылдық ізденіс: Құдайтану баяны. – Алматы: «Ұлттық аударма бюросы» қоғамдық қоры, 2018 жыл – 432 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (97, 'Шульц Д.П., Шульц С.Э. Қазіргі психология тарихы. 11-басылым. Алматы: Ұлттық аударма бюросы, 2018 жыл – 448 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (98, 'Аронсон Эллиот. Көпке ұмтылған жалғыз. Әлеуметтік психологияға кіріспе, 11-басылым. Алматы: «Ұлттық аударма бюросы» қоғамдық қоры, 2018 жыл – 408 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (99, 'Бернард А. Антропология тарихы мен теориясы. Алматы: Ұлттық аударма бюросы, 2018 жыл – 240 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (100, 'Қайыржан К., Сөз - сандық: Қазақтың көне сөздері. - Алматы: "Өнер" баспасы, 2013. - 480 бет. ', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (103, 'Атаулар', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (211, 'Баспа және полиграфия терминдерінің түсіндірме сөздігі / С. Медеубекұлы, Б. Омарова, Р. Әбдиева. - Алматы: «Сөздік-Словарь», 2013. - 232 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (104, 'Психология: энциклопедиялық сөздік', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (105, 'Қазақ зергерлік өнерінің сөздігі / Шойбеков.Р.Н. - Алматы: Ғылым, 1991. - 88 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (106, 'Мәдениаралық қарым-қатынас. Қазақша-орысша терминдер оқу сөздігі / құраст.: Г.Б. Мадиева, Ж.Р. Сейітметова, М.М. Мәмбетова, Д.Б. Мәдиева. – Алматы: Қазақ университеті, 2015. – 89 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (107, 'Әлеуметтік лингвистика сөздігі / Абасилов А. – Алматы, 2016.-168 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (108, 'Цитология, гистология, эмбриология терминдерінің түсіндірме сөздігі / Сапаров Қ.Ə., Базарбаева Ж.М., Абдуллаева Б.А. Оқу құралы. – Алматы: Экономика, 2012. – 454 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (109, 'Абай пайдаланған басқа тілдер сөздігі / Нұрғали Р. Шығармалары. Т.8. Мақалалар, сөздіктер және биобиблиографиялық көрсеткіш. – Астана: Фолиант, 2013. – 320 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (110, 'Қазақша-немісше дипломатиялық анықтамалар сөздігі / Құраст.: Əділбек Əлжанов. – Алматы: «Қазығұрт» баспасы, 2013.– 176 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (111, 'Паталогиялық анатомия сөздігі', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (112, 'Бабалар сөзі: Жүз томдық.—Астана: «Фолиант», 2004. Т. 1: Хикаялық дастандар.—2004.—360 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (113, 'Білімгерлер мен талапкерлерге, бакалаврлар мен магистрларға, оқытушыларға арналған глоссарий / Үркімбаев М.Ф., Ахметов Ә.С. – Тараз: Тараз университеті, 2011. – 116 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (114, 'Азаматтық құқықтық пәндер бойынша терминологиялық сөздік / Г.А. Жаналинов, Ш.А. Алиев. - Қарағанды, 2013. -193 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (115, 'Исламдық терминдер сөздігі / Құраст.: М.Исахан, М.Муслимов, С.Көкенай, Б.Сыддықов. – Астана: Дін мәселелері жөніндегі ғылыми-зерттеу және талдау орталығы, 2015. – 60 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (116, 'Бабалар сөзі: Жүз томдық.—Астана: «Фолиант», 2004. Т. 2: Хикаялық дастандар.—2004.—360 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (117, 'Интернет психологиясы: ғылыми басылым / П. Уоллейс. - Алматы : Ұлттық аударма бюросы, 2019. - 392 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (118, 'HR менеджментке кіріспе / Уилтон Ник. –Алматы: Ұлттық аударма бюросы, 2019 жыл. – 532 бет', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (119, 'Халықаралық бизнес: Жаһандық нарықтағы бәсеке. 12басылым / Хилл Чарльз, Халт Томас. –  Алматы: Ұлттық аударма бюросы. –  2019. –  720 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (120, 'Ұйымдық мінез-құлық негіздері, 14-басылым / Роббинс Стивен, Джадж Тимати. – Алматы: «Ұлттық аударма бюросы» қоғамдық қоры, 2019 жыл – 488 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (121, 'Panorama: Дүниежүзі тарихы, 2-кітап / Данн Росс Е. – Алматы: Ұлттық аударма аударма бюросы, 2019. – 492 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (122, 'Стратегиялық менеджмент негіздері: бәсекелік артықшылыққа ұмтылу / Гэмбл Джон, Питереф Маргарет, Томпсон Артур. –Алматы: «Ұлттық аударма бюросы» қоғамдық қоры, 2019. – 544 бет', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (123, 'Медиа және журналистика: теория мен практикаға жаңа көзқарас / Бейнбриж Жейсон, Гок Никола, Тайнан Лиз. – Алматы: «Ұлттық аударма бюросы» қоғамдық қоры, 2019. – 592 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (124, 'Дипломатия: коммуникация және халықаралық тәртіп негіздері / Трагер Роберт. –Алматы: Ұлттық аударма бюросы. – 2019. – 256 бет', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (125, 'Әдебиет теориясы: Кіріспе / Райан Майкл. – Алматы: «Ұлттық аударма бюросы» қоғамдық қоры, 2019. – 292 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (126, 'Тіл – инстинкт /  Пинкер Стивен. – Алматы: «Ұлттық аударма бюросы» қоғамдық қоры, 2019 жыл. – 386 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (127, 'Қазақша әскери терминдерінің түсіндірме сөздігі / Аманжолов К., Тасболатов А.: ­ Алматы, «Білім», 1999. -92 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (128, 'Бриикерхоф Д, Уейтс P., Ортега С. Әлеуметтану негіздері, 9-басылым. Алматы: Ұлттық аударма бюросы, 2018 жыл - 464 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (129, 'Әдебиет теориясы: Антология. 2-том /Джули Ривкин мен Майкл Райанның редакциясымен. – Алматы: «Ұлттық аударма бюросы» қоғамдық қоры, 2019. – 372 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (130, 'Қазақ дәстүрлі мәдениетінің энциклопедиялық сөздігі. - Алматы: &quot;Сөздік-Словарь&quot;. 1997.- 368 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (131, 'Фромкин В., Родман Р., Хайамс Н. Тіл біліміне кіріспе, 10-басылым, Халықаралық басылым. Алматы: Ұлттық аударма бюросы, 2018. – 608 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (132, 'Қазақ дәстүрлі мәдениетінің энциклопедиялық сөздігі. - Алматы: &quot;Сөздік-Словарь&quot;. 1997.- 368 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (133, 'Сұрағанова С.К., Сабатаева Б.О. Туризм менеджменті: Туризм мамандығына арналған оқулық. - Алматы: 2002.- 256 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (134, 'Куратко Д.Ф. Кәсіпкерлік: теория, процесс, практика. Алматы: Ұлттық аударма бюросы, 2018. - 465 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (135, 'Саяси түсіндірме сөздік. - Алматы, 2007. - 616 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (136, 'Төтенше жағдайлар және азаматтық қорғаныс: Энциклопедиялық анықтамалық. / Бас ред. Б.Ө. Жақып. – Алматы: «Қазақ энциклопедиясы», 2011. – 640 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (137, 'Криминологиялық терминдердің түсіндірме сөздігі. / Нәбиев Ж.Н.– Орал: М.Өтемісов атындағы БҚМУ редакциялық баспа орталығы, 2013. – 87 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (138, 'Бабалар сөзі: Жүзтомдық. - Астана: «Фолиант», 2013. Т. 100: Ән-өлеңдер. - 440 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (139, 'Бабалар сөзі: Жүзтомдық. - Астана: «Фолиант», 2013. Т. 99: Ән-өлеңдер. - 440 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (140, 'Бабалар сөзі: Жүзтомдық. - Астана: «Фолиант», 2013. Т. 98: Күлдіргі әңгімелер. - 440 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (141, 'Бабалар сөзі: Жүзтомдық. - Астана: «Фолиант», 2013. Т. 97: Ауызекі әңгімелер. - 440 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (142, 'Бабалар сөзі: Жүзтомдық. - Астана: «Фолиант», 2013. Т. 96: Ауызекі әңгімелер. - 432 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (143, 'Бабалар сөзі: Жүзтомдық. - Астана: «Фолиант», 2013. Т. 94: Түс жору және ырымдар. - 432 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (144, 'Бабалар сөзі: Жүз томдық. - Астана: «Фолиант», 2006. Т. 31: Хикаялық дастандар. - 2006. - 376 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (145, 'Бабалар сөзі: Жүз томдық. - Астана: «Фолиант», 2006. Т. 32: Шежірелік дастандар. - 2006. - 400 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (146, 'Бабалар сөзі: Жүз томдық. - Астана: «Фолиант», 2006. Т. 33: Батырлар жыры. - 364 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (147, 'Бабалар сөзі: Жүз томдық. - Астана: «Фолиант», 2006. Т. 34: Батырлар жыры. - 384 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (148, 'Бабалар сөзі: Жүз томдық. - Астана: «Фолиант», 2006. Т. 35: Батырлар жыры. - 2006. - 392 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (149, 'Бабалар сөзі: Жүз томдық. - Астана: «Фолиант», 2006. Т. 36: Батырлар жыры. - 2006. - 480 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (150, 'Бабалар сөзі: Жүз томдық. - Астана: «Фолиант», 2006. Т. 37: Батырлар жыры. - 2006. - 540 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (151, 'Бабалар сөзі: Жүз томдық. - Астана: «Фолиант», 2006. Т. 38: Батырлар жыры. - 2006. - 332 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (152, 'Бабалар сөзі: Жүз томдық. - Астана: «Фолиант», 2006. Т. 39: Батырлар жыры. - 2006. - 448 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (153, 'Бабалар сөзі: Жүз томдық. - Астана: «Фолиант», 2006. Т. 40: Батырлар жыры. - 2006. - 488 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (154, 'Бабалар сөзі: Жүз томдық. - Астана: «Фолиант», 2007. Т. 41: батырлар жыры. - 2007. - 448 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (155, 'Инженерлік ізденістер. Атаулар мен ұғымдардың қазақша-орысша анықтамалық сөздігі. Бакенов Б.Б. – Астана: Л.Н. Гумилев атындағы ЕҰУ баспасы, 2017. – 399 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (156, 'Тіл білімі терминдерінің орысша–қазақша сөздігі. С.Кеңесбаев, Т.Жанұзақов. – Алма-ата. Қазақ ССР–нің «Ғылым» баспасы, 1966. – 211 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (157, 'Діни терминдер сөздігі. Мухитдинов Р.С. – Алматы: 2012. – 140 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (158, 'Қазақ тілі терминдерінің салалық ғылыми түсіндірме сөздігі: Қоғамдық тамақтандыру. – Алматы: &quot;Мектеп&quot; баспасы, 2007. – 232 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (159, 'Ұн тағамдық атауларының анықтағыш сөздігі / Д.Е. Капанова. – Павлодар: Кереку, 2012. – 55 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (160, 'Бабалар сөзі: Жүз томдық.—Астана: «Фолиант», т. 42: Батырлар жыры. – 2007. – 432 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (161, 'Бабалар сөзі: Жүз томдық. – Астана: «Фолиант», т. 43: Батырлар жыры. – 2007. – 416 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (162, 'Бабалар сөзі: Жүз томдық. – Астана: «Фолиант», т. 44: Батырлар жыры. – 2007. – 496 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (163, 'Бабалар сөзі: Жүз томдық. – Астана: «Фолиант», т. 45: Батырлар жыры. – 2007. – 464 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (164, 'Бабалар сөзі: Жүз томдық. – Астана: «Фолиант», т. 46: Батырлар жыры. – 2008. – 512 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (165, 'Бабалар сөзі: Жүз томдық.– Астана: «Фолиант», т. 47: Батырлар жыры. – 2008.– 424 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (166, 'Бабалар сөзі: Жүзтомдық. – Астана: «Фолиант», т. 48: Батырлар жыры.  – 2008. – 536 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (167, 'Бабалар сөзі: Жүз томдық. – Астана: «Фолиант», т. 49: Батырлар жыры.  – 2008. – 416 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (168, 'Бабалар сөзі: Жүзтомдық. – Астана: «Фолиант», т. 50: Батырлар жыры. – 2008. – 464 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (169, 'Бабалар сөзі: Жүзтомдық. – Астана: «Фолиант», т. 51: Батырлар жыры.  – 2008. – 448 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (170, 'Бабалар сөзі: Жүзтомдық. – Астана: «Фолиант», т. 52: Көне эпос.  – 2008. – 352 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (171, 'Бабалар сөзі: Жүзтомдық. – Астана: «Фолиант», т. 53: Ғашықтық жырлар.  –  2009. – 456 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (172, 'Бабалар сөзі: Жүзтомдық. – Астана: «Фолиант», т. 54: Ғашықтық жырлар.  –  2009. – 456 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (173, 'Бабалар сөзі: Жүзтомдық. – Астана: «Фолиант», т. 55: Ғашықтық жырлар.  –  2009. – 384 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (174, 'Бабалар сөзі: Жүзтомдық. – Астана: «Фолиант», т. 56: Тарихи жырлар.  –  2009. – 408 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (175, 'Бабалар сөзі: Жүзтомдық. – Астана: «Фолиант», т. 57: Тарихи жырлар. –  2009. – 408 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (176, 'Бабалар сөзі: Жүзтомдық. – Астана: «Фолиант», т. 58: Тарихи жырлар. – 2010.  – 432 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (177, 'Бабалар сөзі: Жүзтомдық.  – Астана: «Фолиант», т. 59: Тарихи жырлар. – 2010. – 400 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (178, 'Бабалар сөзі: Жүзтомдық. – Астана: «Фолиант», т. 60: Тарихи жырлар. – 2010. – 448 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (179, 'Бабалар сөзі: Жүзтомдық. – Астана: Фолиант, т. 61: Тарихи жырлар. – 2010. – 448 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (180, 'Бабалар сөзі: Жүзтомдық. – Астана: Фолиант, т. 62: Тарихи жырлар. – 2010. – 376 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (181, 'Бабалар сөзі: Жүзтомдық. – Астана: Фолиант, т. 63: Тарихи жырлар. – 2010. – 456 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (182, 'Бабалар сөзі: Жүзтомдық. – Астана: «Фолиант», т. 64: Жұмбақтар. – 2010. – 432 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (183, 'Бабалар сөзі: Жүзтомдық. – Астана: «Фолиант», т. 65: Қазақ мақал–мәтелдері. – 2010. – 488 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (184, 'Физика. Орысша-қазақша түсіндірме сөздік / Жалпы ред. Басқарған э.ғ.д., профессор Е. Арын - Павлодар: Павлодар: «Кереку» баспасы, 2011. – 449 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (185, 'Сапа менеджмент  жүйесінің терминдері мен анықтамалар сөздігі / С.Ж.Асфендияров атындағы Қазақ ұлттық медицина университеті, Сапа менеджмент жүйесі бөлімі әзірлеген сөздік.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (186, 'Стандарттау, сертификаттау және метрология негіздері. Ж.Ж. Есенқұлова, Ж.Ж. Аканова, А.М. Касенова: Оқу құралы / Алматы: Экономика, 2014. -284 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (187, 'Халықаралық экономика бойынша терминологиялық сөздігі / Жетпісбаева Б.А., Есенгельдин Б.С., Хусаинова Ж.С., Жартай Ж.М. – Қарағанды: ҚарМУ баспасы, 2016. – 181 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (188, 'Физиология терминдерінің түсіндірме сөздігі / Несіпбаев Т. 2-басылым. - Алматы: «Агроуниверситет» баспасы, 2004. - 226 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (189, 'Орысша-қазақша ветеринарлық сөздік / Джанабеков К., Джанабекова Г.К. – Алматы, «Сөздік-Словарь», 2013, - 288 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (190, 'Тарих пәндер бойынша түсініктер мен терминдер. Жоғары оқу орындарына арналған оқу-әдістемелік құрал. – Алматы: Қазақ университеті, 2014. – 43 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (191, 'Биотехнология: Оқулық / Аубакиров Х. Ə. - Алматы: ЖШС РПБК «Дəуір», 2011.- 368 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (192, 'Гендерлік терминология сөздігі. ҚазМемҚызПУ Әлеуметтік және гендерлік ғылыми-зерттеулер институты ұсынған.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (193, 'Музыка мәдениеті мен өнер терминдерінің сөздігі / Б.Ж.Қоқымбаева, Е.Ю.Личман, Б.У.Итемгенова. – Павлодар, ПМПИ, 2013. – 177 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (194, 'Сақтандыру терминдер сөздігі. «Виктория» Сақтандыру компаниясы ұсынған.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (195, 'Психология: Энциклопедиялық сөздік / Бас ред. Б.Ө. Жақып. - Алматы: «Қазақ энциклопедиясы», 2011. - 624 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (196, 'Қаржы. Оқу құралы / А.М.Көкебаева , Е.Ж.Оспанов, Қ.Мырзабекқызы, Г.Д.Алиева. Түркістан, «Тұран» 2009 ж. - 197 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (197, 'Мемлекеттік қаржы: Оқу құралы/ Н.Т.Сартанова,А.К.Абжанова - Қостанай: А.Байтұрсынов атындағы ҚМУ, 2016. - 190 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (198, 'Қазақ әдеби тілінің анықтамалығы / Құрастырған: С.А.Итеғұлова, А.Қ.Қожахмет. - Астана: Ш.Шаяхметов атындағы тілдерді дамытудың республикалық үйлестіру- әдістемелік орталығы, 2016. – 150 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (199, 'Қазақ тіліндегі қысқарған сөздер./Құрманбайұлы Ш. – Алматы, 2013. - 296 бет.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (200, 'Психология: Энциклопедиялық сөздік./Бас ред.Б.Ө.Жақып.-Алматы', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (201, 'Ғылым тарихы мен философиясы: магистранттарға арналған оқу құралы / Д.Б. Тойматаев. - Қостанай: ҚР ІІМ Ш. Қабылбаев атындағы Қостанай академиясы, 2016. – 209 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (202, 'Web-дизайн негіздері: жоғарғы оқу орындарының студенттеріне арналған оқу құралы / Айтбенова А.А. – Қостанай: ҚМПИ, 2015. – 237 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (203, 'Геоақпараттық жүйе негіздері / Ахметов Е.М., Кунаев М.С. – Алматы: «Арыс» баспасы, 2008. – 208 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (204, 'Мұғалімге арналған нұсқаулық. – Астана: «Назарбаев Зияткерлік мектептері» ДББҰ Педагогикалық шеберлік орталығы. 2016. – 102 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (205, 'Арабша-қазақша түсіндірме сөздік. Қазақ тіліндегі араб сөздері / Н.Д. Оңдасынов. 1-том. Алматы: «Білім», 2010. – 167 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (206, 'Қазақ тілінің кірме сөздер сөздігі / Құрастырғандар: Ш. Құрманбайұлы, С.Исақова, Б.Мизамхан және т.б. Алматы: «Ұлттық аударма бюросы» қоғамдық қоры, 2019. – 596 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (212, 'Қазақ әдеби тілінің сөздігі. Он бес томдық. 8 - том / Құраст.: Қ. Күдеринова, О.Жұбаева, М. Жолшаева және т.б. - Алматы, 2011. - 744 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (213, 'Қазақстан Республикасы қолданыстағы заңдарының заң терминдері мен ұғымдарының сөздігі. – Астана: «Қазақстан Республикасының Заң шығару институты» ЖШС, 2007. – 1000 б.', UNIX_TIMESTAMP(), 0);
INSERT IGNORE INTO qsource (id, title, addTime, qStatus) VALUES (214, '', UNIX_TIMESTAMP(), 0);
COMMIT;
