<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>QType.Web</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="MySqlConnector" Version="2.3.7" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../QType.COMMON/QType.COMMON.csproj" />
    <ProjectReference Include="../QType.MODEL/QType.MODEL.csproj" />
    <ProjectReference Include="../QType.DBHelper/QType.DBHelper.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.Local.json" Condition="Exists('appsettings.Local.json')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
