<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="Dapper.SimpleCRUD" Version="2.3.0" />
    <PackageReference Include="MySqlConnector" Version="2.3.7" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../QType.COMMON/QType.COMMON.csproj" />
    <ProjectReference Include="../QType.MODEL/QType.MODEL.csproj" />
  </ItemGroup>
</Project>
